# Generated by Django 2.1.5 on 2019-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=30)),
                ('account_no', models.CharField(max_length=30)),
                ('IFSC', models.CharField(max_length=30)),
                ('atm_card_no', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=5)),
                ('atm_pin', models.CharField(max_length=5)),
                ('card_expiry', models.CharField(max_length=5)),
                ('net_banking_id', models.CharField(max_length=30)),
                ('signin_password', models.CharField(max_length=30)),
                ('transaction_password', models.CharField(max_length=30)),
                ('mob_banking_pin', models.CharField(max_length=30)),
            ],
        ),
    ]
