# Generated by Django 2.1.5 on 2019-12-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default='Pavan Jain', max_length=30),
        ),
    ]
