# Generated by Django 2.1.5 on 2019-12-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bankaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
